// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rpcclient} from '../models';

export function Spin(arg1:number):Promise<rpcclient.SpinResult>;
